name: Refresh test & build cache & build latest
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-cache-refresh:
    timeout-minutes: 720
    name: Build test cache and push images
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout source
        uses: actions/checkout@v5

      - name: Prep for build
        run: |
          echo "${{ github.sha }}" >SOURCE_VERSION
          echo "ENVOY_MINOR_RELEASE=$(cat ENVOY_VERSION | sed 's/envoy-\([0-9]\+\.[0-9]\+\)\..*/v\1/')" >> $GITHUB_ENV
          echo "ENVOY_PATCH_RELEASE=$(cat ENVOY_VERSION | sed 's/^envoy-\([0-9]\+\.[0-9]\+\.[0-9]\+$\)/v\1/')" >> $GITHUB_ENV
          echo "BUILDER_DOCKER_HASH=$(git ls-tree --full-tree HEAD -- ./Dockerfile.builder | awk '{ print $3 }')" >> $GITHUB_ENV

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/buildx-cache
          key: docker-cache-tests

      - name: Clear cache
        run: rm -rf /tmp/buildx-cache/*

      - name: Run integration tests on amd64 to update docker cache
        uses: docker/build-push-action@v6.18.0
        id: docker_tests_ci_cache_update
        with:
          provenance: false
          context: .
          file: ./Dockerfile.tests
          platforms: linux/amd64
          build-args: |
            BUILDER_BASE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cilium-envoy-builder:${{ env.BUILDER_DOCKER_HASH }}
          cache-to: type=local,dest=/tmp/buildx-cache,mode=max
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cilium-envoy:latest-testlogs

  build-cache-and-push-images:
    timeout-minutes: 720
    name: Build cache and push images
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout source
        uses: actions/checkout@v5

      - name: Prep for build
        run: |
          echo "${{ github.sha }}" >SOURCE_VERSION
          echo "ENVOY_MINOR_RELEASE=$(cat ENVOY_VERSION | sed 's/envoy-\([0-9]\+\.[0-9]\+\)\..*/v\1/')" >> $GITHUB_ENV
          echo "ENVOY_PATCH_RELEASE=$(cat ENVOY_VERSION | sed 's/^envoy-\([0-9]\+\.[0-9]\+\.[0-9]\+$\)/v\1/')" >> $GITHUB_ENV
          echo "BUILDER_DOCKER_HASH=$(git ls-tree --full-tree HEAD -- ./Dockerfile.builder | awk '{ print $3 }')" >> $GITHUB_ENV
          echo "SOURCE_TIMESTAMP=$(git log -1 --pretty=format:'%ct' .)" >> $GITHUB_ENV

      - name: Multi-arch build & push Builder image
        uses: docker/build-push-action@v6.18.0
        id: docker_build_builder
        with:
          provenance: false
          context: .
          file: ./Dockerfile.builder
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cilium-envoy-builder:${{ env.BUILDER_DOCKER_HASH }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cilium-envoy-builder:latest

      - name: Multi-arch build & push main image
        uses: docker/build-push-action@v6.18.0
        id: docker_build_cd
        with:
          provenance: false
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILDER_BASE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cilium-envoy-builder:${{ env.BUILDER_DOCKER_HASH }}
          cache-to: type=local,dest=/tmp/buildx-cache,mode=max
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cilium-envoy:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cilium-envoy:${{ github.sha }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/cilium-envoy:${{ env.ENVOY_PATCH_RELEASE }}-${{ github.sha }}
